In [1]:
import numpy as np

In [2]:
arr =np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr =np.array([[10,20,30],[40,50,60],[50,60,70]])

In [6]:
print(arr)

[[10 20 30]
 [40 50 60]
 [50 60 70]]


In [9]:
arr=np.array([10,20,30,40])
print(arr[0])

10


In [10]:
print(arr[0:2])

[10 20]


In [11]:
print(arr[-1])

40


In [12]:
print(arr[::-1])

[40 30 20 10]


In [41]:
arr =np.arange(1,17)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [42]:
matrix =arr.reshape(4,4)

In [49]:
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [53]:
print(matrix[0]) #first row


[1 2 3 4]


In [54]:
print(matrix[1]) #second row

[5 6 7 8]


In [56]:
matrix[:,0] #first colum

array([ 1,  5,  9, 13])

In [57]:
matrix[:,1] #second column

array([ 2,  6, 10, 14])

In [48]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
matrix[:2,:2]

array([[1, 2],
       [5, 6]])

In [59]:
matrix[2:,2:]

array([[11, 12],
       [15, 16]])

In [60]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
matrix[2:,1:3]

array([[10, 11],
       [14, 15]])

In [63]:
matrix[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [65]:
arr.shape


(16,)

In [66]:
matrix.shape

(4, 4)

In [67]:
matrix[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [68]:
matrix[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [69]:
matrix[::-1]

array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [70]:
matrix[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [71]:
matrix[0:2, 0:2] = 100
print(matrix)

[[100 100   3   4]
 [100 100   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]]


In [72]:
tensor = np.arange(27).reshape(3, 3, 3)

In [73]:
tensor

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [76]:
tensor[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
tensor[:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [81]:
tensor[0, :, :]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
tensor[:, 1, :]

array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]])

In [84]:
tensor[:, :, 2]   # All 3rd columns

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [85]:
tensor

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [87]:
for x in matrix:
    for j in x:
        print(j)


100
100
3
4
100
100
7
8
9
10
11
12
13
14
15
16


In [89]:
arr =np.zeros(10)

In [90]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
arr =np.zeros((4,4))

In [92]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
arr =np.ones(10)

In [94]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [95]:
arr =np.ones((3,3))

In [96]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
arr =np.full(4,10)

In [98]:
arr

array([10, 10, 10, 10])

In [99]:
arr =np.full((4,4),10)

In [100]:
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [104]:
arr =np.eye(10)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [105]:
arr = np.linspace(1,10, 100)
print(arr)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [106]:
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)


(4, 4)
2
16


In [109]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a/b)
print(a *b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[  1  32 729]


In [115]:
arr =np.array([10,20,30,40])
print(f"Max {arr.max()}")
print(f"Min {arr.min()}")
print(f"Mean {arr.mean()}")
print(f"Stdv {arr.std()}")
print(f"Sum {arr.sum()}")

Max 40
Min 10
Mean 25.0
Stdv 11.180339887498949
Sum 100


In [116]:
arr =np.array([10,20,30,40])
print(f"Max {np.max(arr)}")
print(f"Min {np.min(arr)}")
print(f"Mean {np.mean(arr)}")
print(f"Stdv {np.std(arr)}")
print(f"Sum {np.sum(arr)}")

Max 40
Min 10
Mean 25.0
Stdv 11.180339887498949
Sum 100


In [118]:
print(np.argmax(arr))

3


In [119]:
print(np.argmin(arr))

0


In [123]:
print(np.mod(arr,3))

[1 2 0 1]


In [124]:
print(np.fmod(arr,3))

[1 2 0 1]


In [126]:
np.abs([-1,-2,-3,10])

array([ 1,  2,  3, 10])

In [127]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.add(x1, x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [129]:
print(np.all([True,True,True]))

True


In [130]:
print(np.all([True,True,False]))

False


In [131]:
print(np.any([True,True,False]))

True


In [132]:
np.pi

3.141592653589793

In [137]:
print(np.argmax([10,40,20,5]))

1


In [138]:
print(np.argmin([10,40,20,5]))

3


In [139]:
#broadcasting is a powerful mechanism that allows arithmetic operations
#to be performed on arrays with different shapes and sizes
a=np.array([[1],[2],[3]])
b=np.array([4,5])
print(a+b)


[[5 6]
 [6 7]
 [7 8]]


In [197]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

print(np.vstack((a, b)))
print(np.hstack((a, b)))
print(np.concatenate((a, b), axis=0))


[[1 2]
 [3 4]]
[[1 2 3 4]]
[[1 2]
 [3 4]]


In [140]:
a = np.array([1, 2, 3])
b = a 
b[1:]=100
print(a)
print(b)

[  1 100 100]
[  1 100 100]


In [146]:
arr = np.arange(6)
print(np.split(arr,3))


[array([0, 1]), array([2, 3]), array([4, 5])]


In [151]:
arr =np.array([10,40,30,20])
print(np.sort(arr))

[10 20 30 40]


In [153]:
arr.argsort()

array([0, 3, 2, 1])

In [154]:
arr[arr>20]

array([40, 30])

In [155]:
arr = np.array([10, 20, 30, 40, 50])
print(arr>20)

[False False  True  True  True]


In [157]:
print(arr[arr>20])

[30 40 50]


In [158]:
arr[(arr > 20) & (arr < 45)]


array([30, 40])

In [159]:
arr[(arr < 15) | (arr > 45)]


array([10, 50])

In [164]:
print(arr[np.where(arr >30)])

[40 50]


In [167]:
matrix = np.array([[10, 20], [30, 40], [50, 60]])


In [169]:
matrix[matrix >30]

array([40, 50, 60])

In [170]:
arr

array([10, 20, 30, 40, 50])

In [171]:
np.where( arr >20,99,arr)

array([10, 20, 99, 99, 99])

In [172]:
arr

array([10, 20, 30, 40, 50])

In [173]:
mask = (arr % 20 == 0)
arr[mask]

array([20, 40])

In [174]:
arr = np.array([10, 20, 30, 40, 50])

arr[np.isin(arr, [20, 50])]


array([20, 50])

In [175]:
arr = np.array([1, 2, np.nan, 4, 5])
print(arr)

[ 1.  2. nan  4.  5.]


In [179]:
np.isnan(arr)
arr[~np.isnan(arr)]


array([1., 2., 4., 5.])

In [180]:
arr[np.isnan(arr)] = 0
print(arr)

[1. 2. 0. 4. 5.]


In [182]:
arr = np.array([10,20,np.nan,40])
print(arr)


[10. 20. nan 40.]


In [184]:
print(np.mean(arr))

nan


In [185]:
print(np.nanmean(arr))     
print(np.nanmax(arr))      
print(np.nanmin(arr))      
print(np.nansum(arr) )     
print(np.nanstd(arr))      

23.333333333333332
40.0
10.0
70.0
12.472191289246473


In [191]:
matrix = np.array([[1, 2], [np.nan, 4]])
filter=np.isnan(matrix)
print(matrix[~filter])

[1. 2. 4.]


In [1]:
import numpy as np

In [2]:
np.random.rand(4,4) #random samples from a uniform distribution over ``[0, 1)`

array([[0.79063438, 0.52417597, 0.21603902, 0.07032366],
       [0.46132399, 0.09916411, 0.18465984, 0.12040286],
       [0.29350958, 0.44449038, 0.98789253, 0.5305429 ],
       [0.48495025, 0.00740163, 0.78404542, 0.52835116]])

In [4]:
np.random.randint(1,10,5)

array([9, 2, 2, 1, 6], dtype=int32)

In [7]:
np.random.randn(2,4) #Return a sample  from the "standard normal" distribution.


array([[-0.83613706, -0.6571754 , -1.45427231,  0.14343601],
       [-0.42895048, -0.35365369, -1.34481642,  0.77810679]])

In [10]:
a = np.array([[1, 2], [3, 4]])
for x in np.nditer(a):
    print(x)


1
2
3
4


In [12]:
a = np.array([5,0,2, 3, 1,1])
print(np.sort(a))
print(np.argsort(a))
print(np.unique(a))
print(np.count_nonzero(a))



[0 1 1 2 3 5]
[1 4 5 2 3 0]
[0 1 2 3 5]
5


In [13]:
np.save('data.npy', a)
np.load('data.npy')

np.savetxt('data.txt', a)
np.loadtxt('data.txt')


array([5., 0., 2., 3., 1., 1.])