In [6]:
import numpy as np
arr =np.array([10,20,30,40])
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40]
<class 'numpy.ndarray'>
int64


In [7]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr = np.arange(0,11,2)
print(arr)

[ 0  2  4  6  8 10]


In [9]:
print(arr[0])

0


In [10]:
print(arr[0:3])

[0 2 4]


In [11]:
print(arr[2:])

[ 4  6  8 10]


In [12]:
print(arr[:2])

[0 2]


In [14]:
print(arr[::-1])

[10  8  6  4  2  0]


In [15]:
print(arr[::2])

[0 4 8]


In [16]:
arr_copy = arr.copy()

In [17]:
arr_copy

array([ 0,  2,  4,  6,  8, 10])

In [18]:
print(f"memory address arr {id(arr)}")
print(f"memory address for arr_copy {id(arr_copy)}")

memory address arr 2344380157360
memory address for arr_copy 2344380157744


In [23]:
arr_part = arr[2:]
arr_part=arr_part *2
print(arr)
print(arr_part)
print(f"memory address for arr_part {id(arr_part)}")

[ 0  2  4  6  8 10]
[ 8 12 16 20]
memory address for arr_part 2344380158608


In [24]:
arr.shape

(6,)

In [26]:
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
        

In [27]:
print(matrix)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [29]:
print(matrix.shape)

(3, 3)


In [34]:
matrix =np.arange(9).reshape(3,3)

In [35]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
arr =matrix.flatten()

In [37]:
print(arr)

[0 1 2 3 4 5 6 7 8]


In [45]:
arr =np.full((3,3),10)

In [41]:
arr

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [48]:
arr =np.identity(10)

In [54]:
arr =np.eye(10,10,k=2)

In [55]:
arr

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [57]:
matrix =np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120],[130,140,150,160]])

In [58]:
matrix

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [83]:
print(matrix[0][0])

10


In [87]:
matrix[:,1:3]

array([[ 20,  30],
       [ 60,  70],
       [100, 110],
       [140, 150]])

In [88]:
matrix

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [99]:
matrix[2,2]


np.int64(110)

In [67]:
matrix[0:,:2]

array([[ 10,  20],
       [ 50,  60],
       [ 90, 100],
       [130, 140]])

In [70]:
matrix[:2]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [71]:
matrix[0:,2:]

array([[ 30,  40],
       [ 70,  80],
       [110, 120],
       [150, 160]])

In [72]:
matrix

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [73]:
matrix[:2,:2]

array([[10, 20],
       [50, 60]])

In [77]:
matrix[:2,2:]

array([[30, 40],
       [70, 80]])

In [78]:
matrix[2:,2:]

array([[110, 120],
       [150, 160]])

In [79]:
matrix

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [80]:
matrix[1:3,1:3]

array([[ 60,  70],
       [100, 110]])

In [106]:
threeD= np.arange(27).reshape(3,3,3)


In [107]:
print(threeD)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [108]:
threeD.shape

(3, 3, 3)

In [109]:
arr =threeD.flatten()

In [111]:
arr.shape

(27,)

In [112]:
arr = np.zeros(10)

In [113]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [117]:
arr =np.zeros((3,3,4))

In [118]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [119]:
arr =np.ones(10)

In [120]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [123]:
arr =np.ones((4,10,10))

In [124]:
arr

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [125]:
arr =np.identity(10)

In [126]:
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [143]:
arr =np.eye(10,13,k=5)

In [144]:
arr

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [149]:
arr = np.full(10,5)

In [150]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [151]:
arr=np.full((10,10),8)

In [152]:
arr

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [155]:
arr = np.linspace(1,10, 50)

In [156]:
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [163]:
arr1=np.array([10,20,30,40])
arr2=np.array([20,30,40,50])
print(arr2+arr1)
print(arr2-arr1)
print(arr1 * 10)
print(arr1 /2)

[30 50 70 90]
[10 10 10 10]
[100 200 300 400]
[ 5. 10. 15. 20.]


In [167]:
print(np.max(arr1))
print( arr1.max())

40
40


In [168]:
matrix.max()

np.int64(160)

In [195]:
arr1 =np.array([30,20,50,10,40])
print(arr1)
print(f"Max value {np.max(arr1)}")
print(f"Min value {np.min(arr1)}")
print(f"Meen value {np.mean(arr1)}")
print(f"Sum value {np.sum(arr1)}")
print(f"Stdv value {np.std(arr1)}")
print(f"ArgMax value {np.argmax(arr1)}")
print(f"Min value {np.argmin(arr1)}")
print(f"Sqrt value {np.sqrt(arr1)}")
print(f"Power value {np.pow(arr1,2)}")
print(f"Log value {np.log(arr1)}")
print(f"Log2 value {np.log2(arr1)}")
print(f"Log2 value {np.log10(arr1)}")
print(f"abs value {np.abs(arr1)}")
print(f"fabs value {np.fabs(arr1)}")
print(f"Mod value {np.mod(-1,3)}")
print(f"fmod value {np.fmod(-1,3)}")

[30 20 50 10 40]
Max value 50
Min value 10
Meen value 30.0
Sum value 150
Stdv value 14.142135623730951
ArgMax value 2
Min value 3
Sqrt value [5.47722558 4.47213595 7.07106781 3.16227766 6.32455532]
Power value [ 900  400 2500  100 1600]
Log value [3.40119738 2.99573227 3.91202301 2.30258509 3.68887945]
Log2 value [4.9068906  4.32192809 5.64385619 3.32192809 5.32192809]
Log2 value [1.47712125 1.30103    1.69897    1.         1.60205999]
abs value [30 20 50 10 40]
fabs value [30. 20. 50. 10. 40.]
Mod value 2
fmod value -1


In [197]:
print(arr1)
print(np.sort(arr1)[::-1])

[30 20 50 10 40]
[50 40 30 20 10]


In [205]:
arr=np.array([10,20,30,40,50,60])
arr1 =np.split(arr,3)
print(arr1)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [206]:
filter =arr>30

In [210]:
filterd_arr =arr[arr>30]

In [212]:
filterd_arr

array([40, 50, 60])

In [221]:
filtered_arr = arr[(arr>=30) & (arr <=50)]

In [220]:
filtered_arr

array([10, 20, 30, 40, 50, 60])

In [226]:
np.where

(array([3, 4, 5]),)

In [229]:
arr.ndim

1

In [230]:
matrix.ndim

2

In [233]:
threeD.ndim

3

In [234]:
arr.size

6

In [235]:
matrix.size

16

In [236]:
threeD.size

27

In [237]:
arr.itemsize

8

In [238]:
arr.nbytes

48

In [239]:
matrix

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [240]:
matrix.T

array([[ 10,  50,  90, 130],
       [ 20,  60, 100, 140],
       [ 30,  70, 110, 150],
       [ 40,  80, 120, 160]])

In [245]:
arr1=np.arange(0,10)
arr2=np.arange(10,21)
arr3 =np.append(arr1,arr2)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [243]:
arr1

[array([10, 20]), array([30, 40]), array([50, 60]), array([20, 30, 40, 50])]

In [2]:
import numpy as np
arr =np.arange(10)


In [3]:
np.split(arr,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [27]:
np.split(a,2)

[array([[1, 2]]), array([[3, 4]])]

In [28]:
np.split(a,2,axis=1)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [3]:
#random floating-point 
#number between 0.0 (inclusive) and 1.0 (exclusive).
import numpy as np
print(np.random.random())
print(np.random.random((4,4))) 

0.4303024433658208
[[0.05110323 0.53827626 0.09701038 0.97910694]
 [0.3613612  0.73208336 0.12400409 0.36679019]
 [0.11261586 0.27247358 0.20550487 0.00259246]
 [0.96602642 0.36748664 0.65106545 0.2017811 ]]


In [4]:
print(np.random.rand(3,3)) #random samples from a uniform distribution

[[0.29691312 0.76816522 0.27473819]
 [0.32289845 0.54394716 0.96099972]
 [0.34279261 0.34189101 0.60617105]]


In [5]:
print(np.random.randn(3,3)) #array of samples from the normal distribution 

[[ 1.3832261  -0.38251224 -0.2846366 ]
 [ 0.71896096  0.36757947  1.5043603 ]
 [-0.41109995 -0.48530928 -1.88793685]]


In [36]:
np.random.randint(1,100,10)

array([17, 24, 12, 15, 46, 76, 29, 35, 83, 64], dtype=int32)

In [11]:
arr=[10,20,30]
print(np.random.choice(arr))

20


In [13]:
a = np.array([1, 2, 3, 4, 5])
np.random.shuffle(a)
print(a)   # Shuffles in-place


[2 5 4 1 3]


In [25]:
arr = np.arange(9).reshape(3,3)
np.save('c:/python_challenge/numpy1',arr)

In [29]:

arr1 = np.load('c:/python_challenge/numpy1.npy')
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])