In [4]:
import numpy as np
arr = np.array([10,20,30,40])
print(type(arr))
print(arr)
print(arr.dtype)

<class 'numpy.ndarray'>
[10 20 30 40]
int64


In [5]:
arr = np.arange(0,11,2)
print(arr)

[ 0  2  4  6  8 10]


In [6]:
arr[0]

np.int64(0)

In [10]:
print(arr[1:3])

[2 4]


In [11]:
arr[::-1]

array([10,  8,  6,  4,  2,  0])

In [26]:
arr1=arr

In [28]:
arr1[2:4]*4

array([16, 24])

In [29]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [30]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [23]:
arr1*10

array([20, 40, 60])

In [24]:
arr

array([ 0,  2,  4,  6,  8, 10])

In [35]:
matrix =np.array([[10,20,30],[40,50,60],[70,80,90]])

In [37]:
matrix.shape

(3, 3)

In [38]:
arr.shape

(6,)

In [39]:
matrix = np.arange(1,10).reshape(3,3)

In [40]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
threeD=np.arange(27).reshape(3,3,3)

In [43]:
print(threeD.shape)

(3, 3, 3)


In [44]:
print(threeD)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [46]:
arr =matrix.flatten()

In [64]:
matrix =np.arange(1,17).reshape(4,4)

In [66]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
print(matrix[2,2])

11


In [68]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
matrix[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [60]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
matrix[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [63]:
matrix[:2,:2]

array([[1, 2],
       [4, 5]])

In [77]:
arr =np.zeros((3,3,3,3))

In [78]:
arr

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [79]:
arr =np.ones(100)

In [80]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
arr =np.ones((3,3))

In [84]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [85]:
arr = np.identity(10)

In [89]:
arr =np.eye(10, k=2)

In [90]:
arr

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [95]:
arr = np.full((3,3,4), 5)

In [96]:
arr

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [97]:
arr = np.linspace(1,10, 50)

In [98]:
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [102]:
arr1=np.array([10,20,30])
arr2=np.array([20,30,40])
arr = arr1 +arr2
arr3=10
print(arr1 * arr3)

[100 200 300]


In [111]:
arr =np.array([20,10,50,30,40])
print(f"Max { np.max(arr)}")
print(f"Min { np.min(arr)}")
print(f"Mean { np.mean(arr)}")
print(f"Sum { np.sum(arr)}")
print(f"Std { np.std(arr)}")
print( arr.max())
print(f"ArgMax { np.argmax(arr)}")
print(f"ArgMin { np.argmin(arr)}")
print(f"mod { np.mod(arr,2)}")





Max 50
Min 10
Mean 30.0
Sum 150
Std 14.142135623730951
50
ArgMax 2
ArgMin 1
mod [0 0 0 0 0]


In [113]:
arr =np.array([-1,-2,20])
print(f"abs { np.abs(arr)}")
print(f"abs { np.fabs(arr)}")


abs [ 1  2 20]
abs [ 1.  2. 20.]


In [117]:
arr =np.arange(1,6)
print(f"Pi { np.pi}")
print(f"abs { np.sqrt(arr)}")
print(f"Log { np.log(arr)}")
print(f"Log2 { np.log2(arr)}")
print(f"Log10 { np.log10(arr)}")
print(f"abs { np.pow(arr,2)}")





Pi 3.141592653589793
abs [1.         1.41421356 1.73205081 2.         2.23606798]
Log [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Log2 [0.         1.         1.5849625  2.         2.32192809]
Log10 [0.         0.30103    0.47712125 0.60205999 0.69897   ]
abs [ 1  4  9 16 25]


In [118]:
matrix.ndim

2

In [119]:
arr.ndim

1

In [120]:
threeD.ndim

3

In [121]:
arr.size

5

In [122]:
arr.nbytes

40

In [123]:
arr.itemsize

8

In [125]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [126]:
matrix.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [133]:
np.sort(arr)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [134]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7
8
