In [31]:
import numpy as np


In [32]:
print(np.random.random(10)) #returns a random floating number between 0 and 1

[0.65654297 0.37228334 0.71366411 0.71034123 0.2094864  0.25732005
 0.28538078 0.42544233 0.53486981 0.31448074]


In [6]:
print(np.random.random((4,4)))

[[0.22969404 0.64459075 0.69600483 0.59663546]
 [0.6935898  0.58165633 0.03304014 0.40005344]
 [0.25418497 0.66940761 0.06468186 0.67510994]
 [0.46405936 0.9757032  0.82389346 0.9780207 ]]


In [11]:
print(np.random.randn(10)) #generates random samples from a standard normal distribution

[ 1.10594277  1.17149663  0.48087746 -0.9717448  -0.40734594 -0.55103307
 -1.32454005 -1.26708569 -0.02083305 -0.06065841]


In [15]:
print(np.random.rand(10 )) #generate random numbers from a uniform distribution over the interval [0, 1)

[0.83950317 0.70634333 0.30616963 0.30279396 0.70628118 0.21735929
 0.73721488 0.49697019 0.13742479 0.09440563]


In [19]:
print(np.random.randint(1,100,10)) #random integer

[32 43 85 27 79 97 52 67 39 89]


In [20]:
lst =[10,20,30,40]
print(np.random.choice(lst))

30


In [22]:
np.random.shuffle(lst)
print(lst)

[40, 20, 10, 30]


In [35]:
matrix = np.arange(1,13).reshape(3,4)
np.save('c:/python_challenge/matrix',matrix)

In [36]:
mat = np.load('c:/python_challenge/matrix.npy')


In [37]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
import pandas as pd

In [40]:
s1=pd.Series(data=[10,20,30,40],index=['a','b','c','d'] )

In [44]:
print(s1.index)

Index(['a', 'b', 'c', 'd'], dtype='object')


In [45]:
print(s1.values)

[10 20 30 40]


In [47]:
s1.head(2)

a    10
b    20
dtype: int64

In [48]:
s1.tail(2)

c    30
d    40
dtype: int64

In [49]:
print( s1*2)

a    20
b    40
c    60
d    80
dtype: int64


In [53]:
print(s1.max())

40


In [54]:
print(s1.min())

10


In [55]:
print(s1.mean())

25.0


In [58]:
print( s1.agg(['max','min','mean']))

max     40.0
min     10.0
mean    25.0
dtype: float64


In [60]:
dat=np.arange(1,17).reshape(4,4) *10
col=['A','B','C','D']
ind =['W','X','Y','Z']
df = pd.DataFrame(data=dat, columns=col,index=ind)


In [136]:
dis ={'name':['ram','sham','sheetal','susil','sweeti'],
       'age': [20,31,20,30,20],
       'gender':['M','M','F','M',np.nan],
       'city':['NY','LA','NY','LA','NY'],
       'score':[70,90,80,30,20]
}
df1 = pd.DataFrame(dis)
print(df1)

      name  age gender city  score
0      ram   20      M   NY     70
1     sham   31      M   LA     90
2  sheetal   20      F   NY     80
3    susil   30      M   LA     30
4   sweeti   20    NaN   NY     20


In [65]:
df

A    B    C    D
W   10   20   30   40
X   50   60   70   80
Y   90  100  110  120
Z  130  140  150  160

In [66]:
print(df['A'])

W     10
X     50
Y     90
Z    130
Name: A, dtype: int64


In [67]:
print(df.A)

W     10
X     50
Y     90
Z    130
Name: A, dtype: int64


In [68]:
df[['A','B']]

A    B
W   10   20
X   50   60
Y   90  100
Z  130  140

In [72]:
df.loc[['W','Z']][['A','D']]

A    D
W   10   40
Z  130  160

In [77]:
df.iloc[0:2][['A','D']]

A   D
W  10  40
X  50  80

In [78]:
df.index

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [79]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [80]:
df.values

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [81]:
df.values.dtype

dtype('int64')

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, W to Z
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
 3   D       4 non-null      int64
dtypes: int64(4)
memory usage: 332.0+ bytes


In [84]:
df.describe().T

count   mean        std   min   25%    50%    75%    max
A    4.0   70.0  51.639778  10.0  40.0   70.0  100.0  130.0
B    4.0   80.0  51.639778  20.0  50.0   80.0  110.0  140.0
C    4.0   90.0  51.639778  30.0  60.0   90.0  120.0  150.0
D    4.0  100.0  51.639778  40.0  70.0  100.0  130.0  160.0

In [85]:
df.head()

A    B    C    D
W   10   20   30   40
X   50   60   70   80
Y   90  100  110  120
Z  130  140  150  160

In [86]:
df.head(2)

A   B   C   D
W  10  20  30  40
X  50  60  70  80

In [87]:
df.tail(3)

A    B    C    D
X   50   60   70   80
Y   90  100  110  120
Z  130  140  150  160

In [89]:
df['E']=df['C']+df['D']

In [91]:
df['F']=[100,200,300,400]

In [92]:
df

A    B    C    D    E    F
W   10   20   30   40   70  100
X   50   60   70   80  150  200
Y   90  100  110  120  230  300
Z  130  140  150  160  310  400

In [98]:
df.drop('F', axis=1,inplace=True)

In [99]:
df

A    B    C    D    E
W   10   20   30   40   70
X   50   60   70   80  150
Y   90  100  110  120  230
Z  130  140  150  160  310

In [114]:
df.filter(regex='^W', axis=0)


A   B   C   D   E
W  10  20  30  40  70

In [117]:
df1

name  age gender city  score
0      ram   20      M   NY     70
1     sham   31      M   LA     90
2  sheetal   20      F   NY     80
3    susil   30      M   LA     30
4   sweeti   20      F   NY     20

In [124]:
df_f=df1[(df1['city']=='NY') | (df1['score'] > 70) ]
print(df_f)

      name  age gender city  score
0      ram   20      M   NY     70
1     sham   31      M   LA     90
2  sheetal   20      F   NY     80
4   sweeti   20      F   NY     20


In [131]:
df_f=df1[df1['name'].isin(['ram','sham']) ]
print(df_f)

   name  age gender city  score
0   ram   20      M   NY     70
1  sham   31      M   LA     90


In [133]:
df_f=df1[~df1['name'].isin(['ram','sham']) ]
print(df_f)

      name  age gender city  score
2  sheetal   20      F   NY     80
3    susil   30      M   LA     30
4   sweeti   20      F   NY     20


In [135]:
df_f=df1[~df1['score'].between(70,100) ]
print(df_f)

     name  age gender city  score
3   susil   30      M   LA     30
4  sweeti   20      F   NY     20


In [140]:
df1[df1['gender'].isnull()]

name  age gender city  score
4  sweeti   20    NaN   NY     20

In [141]:
df1[df1['gender'].notnull()]

name  age gender city  score
0      ram   20      M   NY     70
1     sham   31      M   LA     90
2  sheetal   20      F   NY     80
3    susil   30      M   LA     30

In [151]:
df1.query("score.between(10,20)")

name  age gender city  score
4  sweeti   20    NaN   NY     20

In [154]:
df1['score'].max()

np.int64(90)

In [156]:
df1['score'].agg(['max','min','mean','sum'])

max      90.0
min      20.0
mean     58.0
sum     290.0
Name: score, dtype: float64

In [159]:
df1.groupby('city')['score'].max()

city
LA    90
NY    80
Name: score, dtype: int64

In [165]:
df_group=df1.groupby(['gender','city'])
df_group['score'].agg(['max','min','sum','count','std'])

max  min  sum  count        std
gender city                                 
F      NY     80   80   80      1        NaN
M      LA     90   30  120      2  42.426407
       NY     70   70   70      1        NaN

In [174]:
df1.sort_values(['score'])

name  age gender city  score
4   sweeti   20    NaN   NY     20
3    susil   30      M   LA     30
0      ram   20      M   NY     70
2  sheetal   20      F   NY     80
1     sham   31      M   LA     90